security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # This is important! It allows Admins to access Client pages (like the dashboard)
  role_hierarchy:
    ROLE_ADMIN: ROLE_CLIENT

  providers:
    app_users:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_users
      custom_authenticator: App\Security\AppCustomAuthenticator

      logout:
        path: app_logout
        # This redirects to the Home Page after logout (Solving the "Please sign in" issue)
        target: app_home

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
        always_remember_me: true


  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/client/dashboard, roles: ROLE_CLIENT }
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/inscription, roles: PUBLIC_ACCESS }
    - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10